# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainMenuWindow(object):
    def setupUi(self, Main_menu_window):
        Main_menu_window.setObjectName("Main_menu_window")
        Main_menu_window.resize(436, 320)
        self.widget = QtWidgets.QWidget(Main_menu_window)
        self.widget.setGeometry(QtCore.QRect(40, 70, 317, 181))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.new_game_btn = QtWidgets.QPushButton(self.widget)
        self.new_game_btn.setObjectName("new_game_btn")
        self.horizontalLayout_2.addWidget(self.new_game_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.join_game_btn = QtWidgets.QPushButton(self.widget)
        self.join_game_btn.setObjectName("join_game_btn")
        self.horizontalLayout_2.addWidget(self.join_game_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.ai_game_btn = QtWidgets.QPushButton(self.widget)
        self.ai_game_btn.setObjectName("ai_game_btn")
        self.horizontalLayout_3.addWidget(self.ai_game_btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Main_menu_window)
        QtCore.QMetaObject.connectSlotsByName(Main_menu_window)

    def retranslateUi(self, Main_menu_window):
        _translate = QtCore.QCoreApplication.translate
        Main_menu_window.setWindowTitle(_translate("Main_menu_window", "SeaWars_mainMenu"))
        self.label.setText(_translate("Main_menu_window", "Добро пожаловать, PlayerName"))
        self.new_game_btn.setText(_translate("Main_menu_window", "Create room"))
        self.join_game_btn.setText(_translate("Main_menu_window", "Join game"))
        self.ai_game_btn.setText(_translate("Main_menu_window", "Play VS AI"))
