# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qtfiles\room.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_room(object):
    def setupUi(self, room):
        room.setObjectName("room")
        room.resize(485, 450)
        room.setMinimumSize(QtCore.QSize(485, 450))
        self.lineEdit = QtWidgets.QLineEdit(room)
        self.lineEdit.setGeometry(QtCore.QRect(20, 290, 381, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.widget = QtWidgets.QWidget(room)
        self.widget.setGeometry(QtCore.QRect(20, 330, 281, 54))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.back_btn = QtWidgets.QPushButton(self.widget)
        self.back_btn.setMaximumSize(QtCore.QSize(75, 23))
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout_2.addWidget(self.back_btn)
        self.ready_btn = QtWidgets.QPushButton(self.widget)
        self.ready_btn.setObjectName("ready_btn")
        self.horizontalLayout_2.addWidget(self.ready_btn)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.widget1 = QtWidgets.QWidget(room)
        self.widget1.setGeometry(QtCore.QRect(20, 10, 451, 271))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)

        self.retranslateUi(room)
        self.ready_btn.clicked.connect(self.checkBox.click)
        self.lineEdit.textEdited['QString'].connect(self.textBrowser.paste)
        QtCore.QMetaObject.connectSlotsByName(room)

    def retranslateUi(self, room):
        _translate = QtCore.QCoreApplication.translate
        room.setWindowTitle(_translate("room", "SeaWars"))
        self.back_btn.setText(_translate("room", "Back"))
        self.ready_btn.setText(_translate("room", "Ready"))
        self.label.setText(_translate("room", "Чат:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    room = QtWidgets.QWidget()
    ui = Ui_room()
    ui.setupUi(room)
    room.show()
    sys.exit(app.exec_())
